server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  ai:
    mcp:
      server:
        enabled: true
        name: book-management-server
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/message

